# Generated by Django 3.0.5 on 2020-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_samima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samima',
            name='img',
            field=models.ImageField(upload_to='picsofsamima'),
        ),
    ]
