# Generated by Django 3.0.5 on 2020-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_auto_20200710_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bintu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsofbintu')),
            ],
        ),
        migrations.CreateModel(
            name='Isrita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsofisrita')),
            ],
        ),
        migrations.CreateModel(
            name='Mithila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsofmithila')),
            ],
        ),
        migrations.CreateModel(
            name='Puspo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsofpuspo')),
            ],
        ),
        migrations.CreateModel(
            name='Tonima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsoftonima')),
            ],
        ),
    ]
